"""Framework registry module - exports framework registry types."""

# Export from local implementation
# Re-export pipeline registry from framework
from app.ai.framework.pipeline.registry import (
    PipelineRegistry,
    pipeline_registry,
)
from app.ai.framework.registry.stages_registry import (
    StageRegistry,
    clear_all_registries,
    get_agent,
    get_agent_or_raise,
    get_dispatcher,
    get_dispatcher_or_raise,
    get_enricher,
    get_enricher_or_raise,
    get_enrichers_by_domain,
    get_enrichers_by_phase,
    get_guardrails,
    get_guardrails_or_raise,
    get_router,
    get_router_or_raise,
    get_stage,
    get_worker,
    get_worker_or_raise,
    list_agents,
    list_dispatchers,
    list_enrichers,
    list_guardrails,
    list_routers,
    list_stages,
    list_workers,
    register_agent,
    register_dispatcher,
    register_enricher,
    register_guardrails,
    register_router,
    register_stage,
    register_worker,
    stage_registry,
)

__all__ = [
    # Stage registry
    "StageRegistry",
    "stage_registry",
    "register_stage",
    "register_worker",
    "register_dispatcher",
    "register_router",
    "register_enricher",
    "register_agent",
    "register_guardrails",
    "get_stage",
    "get_worker",
    "get_worker_or_raise",
    "get_dispatcher",
    "get_dispatcher_or_raise",
    "get_router",
    "get_router_or_raise",
    "get_enricher",
    "get_enricher_or_raise",
    "get_enrichers_by_domain",
    "get_enrichers_by_phase",
    "get_agent",
    "get_agent_or_raise",
    "get_guardrails",
    "get_guardrails_or_raise",
    "list_stages",
    "list_workers",
    "list_dispatchers",
    "list_routers",
    "list_enrichers",
    "list_agents",
    "list_guardrails",
    "clear_all_registries",
    # Pipeline registry
    "PipelineRegistry",
    "pipeline_registry",
]
